data_paths:
  raw_path: "data/raw/credit_risk_dataset.csv"
  processed_train: "data/processed/train_final.parquet"
  processed_test: "data/processed/test_final.parquet"

schema:
  target: "loan_status"
  numerical_features:
    - "person_age"
    - "person_income"
    - "person_emp_length"
    - "loan_amnt"
    - "loan_int_rate"
    - "cb_person_cred_hist_length"
  categorical_features:
    - "person_home_ownership"
    - "loan_intent"
    - "loan_grade"
    - "cb_person_default_on_file"

validation:
  max_age: 100
  max_emp_length: 60